# This workflow performs a security scan of the repository using CodeQL and sends GitHub notifications.
name: Security Scan and Notify

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * 0'

jobs:
  analyze:
    name: Analyze code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          language: ${{ matrix.language }}

      - name: Upload SARIF results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ github.workspace }}/codeql-report.sarif

      - name: Check for vulnerabilities
        id: check_vulns
        run: |
          # Use jq to parse the SARIF file and count the number of results with severity >= "high"
          VULN_COUNT=$(jq '.runs[].results |  map(select(.level == "error" or .level == "warning")) | length' ${{ github.workspace }}/codeql-report.sarif)
          echo "VULN_COUNT=$VULN_COUNT" >> $GITHUB_ENV
          if [ $VULN_COUNT -gt 0 ]; then
            echo "::set-output name=vulnerable::true"
            echo "Vulnerabilities detected: $VULN_COUNT"
            echo "::warning title=Security Vulnerabilities Detected!::Code scanning has found $VULN_COUNT vulnerabilities in the repository. Please check the Code Scanning alerts in GitHub: ${{ github.server_url }}/${{ github.repository }}/security/code-scanning"
          else
            echo "::set-output name=vulnerable::false"
            echo "No vulnerabilities detected."
          fi
    strategy:
      matrix:
        language: [ 'javascript-typescript', 'python' ]
